# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "web" do |web|
  	web.vm.box = "envimation/ubuntu-xenial"
	web.vm.network "forwarded_port", guest: 80, host: 8081
  	web.vm.provision "shell", path: "install-apache.sh"
	web.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '386' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '1' ]
		vb.customize [ 'modifyvm', :id, '--name', 'web' ]
  	end
  end
  config.vm.define "db" do |db|
  	db.vm.box = "envimation/ubuntu-xenial"
  	db.vm.provision "shell", path: "install-postgres.sh"
	db.vm.provider :virtualbox do |vb|
		vb.customize [ 'modifyvm', :id, '--memory', '512' ]
		vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
		vb.customize [ 'modifyvm', :id, '--name', 'db' ]
  	end
  end
end